data:
    columns:
        clients:
            {
                # 'clnt_id': 'str',
                'accnt_id': 'str',
                'gndr': 'int',
                'pnsn_age': 'int',
                'okato': 'int',
                'phn': 'int',
                'email': 'int',
                'lk': 'int',
                'assgn_npo': 'int',
                'assgn_ops': 'int',

                'age': 'int',
                'prvs_npf_flg': 'int',
                'age_agreement_start': int,

                'erly_pnsn_flg': 'int'
            }
